version: "3"
services:
  app:
    dns: 8.8.8.8
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    env_file: .env
    volumes:
      - .:/app
    expose:
      - "8001"
    depends_on:
      - db
      - redis
  web:
    dns: 8.8.8.8
    build:
      context: ./.docker/web
      args:
        DOMAIN: $DOMAIN
        CREDENTIAL: $CREDENTIAL
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./.docker/web/uwsgi_params:/etc/nginx/uwsgi_params
      - ./.docker/web/log:/var/log/nginx
      - ./.credentials:/.credentials
      - ./static:/static
    depends_on:
      - app
  db:
    image: postgres:11
    dns: 8.8.8.8
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgresql:/var/lib/postgresql/data
  redis:
    image: redis:5.0.3
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis:/data
volumes:
  postgresql:
  redis:
